### ISSUE TITLE
Ruby Syntax? 

### ISSUE THREAD

**Issue by robertsimoes** [morkro/atom-emoji-syntax#47]
Would be amazing to get ruby syntax running? If I can already how do I :)?

**Comment by morkro** [comment]
Sure, sounds good @robertsimoes! :)

To support a new language, you would have to add a new language file to [`lib/languages/`](https://github.com/morkro/atom-emoji-syntax/tree/master/lib/languages) and a _test file_ to [`language-tests/`](https://github.com/morkro/atom-emoji-syntax/tree/master/language-tests).

After that, you have to find out which CSS selectors are used per keyword you want to support. Open the Developer Tools in Atom in any Ruby file and look at the code. Not all keywords are always supported, it depends largely on the language package and how it declares keywords. It should be pretty straight forward, but please do reach out to me if you have any questions :)

If you might not find the time to do it or finish it, just let me know and I will add it to the list of requested features.

**Comment by robertsimoes** [comment]
I'm a bit new to apm development but I can try! cloned the repo and ran as a local developer package via `apm link`  throws me an error for 'event-kit' module, any insight?

```
Cannot find module 'event-kit'
Hide Stack Trace
Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/private/var/folders/vc/173fvvjn6sv0gf75wzmsbllr0000gn/T/AppTranslocation/7683E1A9-EDF8-427F-8107-9735168057E3/d/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/private/var/folders/vc/173fvvjn6sv0gf75wzmsbllr0000gn/T/AppTranslocation/7683E1A9-EDF8-427F-8107-9735168057E3/d/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/private/var/folders/vc/173fvvjn6sv0gf75wzmsbllr0000gn/T/AppTranslocation/7683E1A9-EDF8-427F-8107-9735168057E3/d/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/robert/dev/sandbox/atom-emoji-syntax/lib/settings.js:9:17)
    at Module._compile (/private/var/folders/vc/173fvvjn6sv0gf75wzmsbllr0000gn/T/AppTranslocation/7683E1A9-EDF8-427F-8107-9735168057E3/d/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/private/var/folders/vc/173fvvjn6sv0gf75wzmsbllr0000gn/T/AppTranslocation/7683E1A9-EDF8-427F-8107-9735168057E3/d/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/private/var/folders/vc/173fvvjn6sv0gf75wzmsbllr0000gn/T/AppTranslocation/7683E1A9-EDF8-427F-8107-9735168057E3/d/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/robert/.atom/packages/emoji-syntax/lib/main.js:6:34)
    at Module._compile (/private/var/folders/vc/173fvvjn6sv0gf75wzmsbllr0000gn/T/AppTranslocation/7683E1A9-EDF8-427F-8107-9735168057E3/d/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/private/var/folders/vc/173fvvjn6sv0gf75wzmsbllr0000gn/T/AppTranslocation/7683E1A9-EDF8-427F-8107-9735168057E3/d/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/private/var/folders/vc/173fvvjn6sv0gf75wzmsbllr0000gn/T/AppTranslocation/7683E1A9-EDF8-427F-8107-9735168057E3/d/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/private/var/folders/vc/173fvvjn6sv0gf75wzmsbllr0000gn/T/AppTranslocation/7683E1A9-EDF8-427F-8107-9735168057E3/d/Atom.app/Contents/Resources/app.asar/src/package.js:796:27)
    at /private/var/folders/vc/173fvvjn6sv0gf75wzmsbllr0000gn/T/AppTranslocation/7683E1A9-EDF8-427F-8107-9735168057E3/d/Atom.app/Contents/Resources/app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/private/var/folders/vc/173fvvjn6sv0gf75wzmsbllr0000gn/T/AppTranslocation/7683E1A9-EDF8-427F-8107-9735168057E3/d/Atom.app/Contents/Resources/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/private/var/folders/vc/173fvvjn6sv0gf75wzmsbllr0000gn/T/AppTranslocation/7683E1A9-EDF8-427F-8107-9735168057E3/d/Atom.app/Contents/Resources/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/private/var/folders/vc/173fvvjn6sv0gf75wzmsbllr0000gn/T/AppTranslocation/7683E1A9-EDF8-427F-8107-9735168057E3/d/Atom.app/Contents/Resources/app.asar/src/package-manager.js:468:14)
    at /private/var/folders/vc/173fvvjn6sv0gf75wzmsbllr0000gn/T/AppTranslocation/7683E1A9-EDF8-427F-8107-9735168057E3/d/Atom.app/Contents/Resources/app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/private/var/folders/vc/173fvvjn6sv0gf75wzmsbllr0000gn/T/AppTranslocation/7683E1A9-EDF8-427F-8107-9735168057E3/d/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
```

**Comment by morkro** [comment]
Did you `npm install` all dependencies after linking?

**Comment by robertsimoes** [comment]
I am so stupid 😂
